name: every_watch
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: ^3.4.0
  collection: 1.19.0
  easy_debounce: ^2.0.3
  equatable: ^2.0.7
  fl_chart: ^0.70.2
  flutter_animate: ^4.5.2
  flutter_cache_manager: ^3.4.1
  flutter_native_splash: ^2.4.4
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  go_router: ^14.7.2
  google_fonts: ^6.2.1
  http: 1.2.1
  intl: 0.19.0
  json_path: ^0.7.5
  mime_type: ^1.0.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.15
  path_provider_foundation: ^2.4.1
  path_provider_platform_interface: 2.1.2
  provider: 6.1.2
  shared_preferences: ^2.5.1
  shared_preferences_android: ^2.4.4
  shared_preferences_foundation: ^2.5.4
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: ^2.4.2
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.4.1
  sticky_headers: 0.3.0+2
  timeago: ^3.7.0
  universal_io: 2.2.2
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.14
  url_launcher_ios: ^6.3.2
  url_launcher_platform_interface: 2.3.2
  xml: 6.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  high_chart: ^2.3.0
  built_value: ^8.9.0
  flutter_advanced_switch: ^3.1.0
  skeletonizer: ^1.4.3
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  mime: ^2.0.0
  image: ^4.5.2
  flutter_image_compress: ^2.3.0
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  camera: ^0.11.1
  fpdart: ^1.1.1
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  

dependency_overrides:
  http: 1.2.1
  uuid: ^4.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.1.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  built_value_generator: ^8.9.0
  flutter_gen_runner: ^5.9.0
  json_serializable: ^6.9.0

flutter_gen:
  assets:
    enabled: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/icons/
  fonts:
    - family: Hometab
      fonts:
        - asset: assets/fonts/hometab.ttf
    - family: Profile
      fonts:
        - asset: assets/fonts/profile.ttf
    - family: ArrowRight
      fonts:
        - asset: assets/fonts/arrow-right.ttf
    - family: Compare
      fonts:
        - asset: assets/fonts/compare.ttf
    - family: Collection
      fonts:
        - asset: assets/fonts/collection.ttf
    - family: Favorite
      fonts:
        - asset: assets/fonts/favorite.ttf
    - family: Notification
      fonts:
        - asset: assets/fonts/notification.ttf
    - family: Rate
      fonts:
        - asset: assets/fonts/rate.ttf
    - family: Referral
      fonts:
        - asset: assets/fonts/referral.ttf
    - family: Subscription
      fonts:
        - asset: assets/fonts/subscription.ttf
    - family: Currency
      fonts:
        - asset: assets/fonts/currency.ttf
    - family: Support
      fonts:
        - asset: assets/fonts/support.ttf
    - family: Info
      fonts:
        - asset: assets/fonts/info.ttf
    - family: Sort
      fonts:
        - asset: assets/fonts/sort.ttf
    - family: Filter
      fonts:
        - asset: assets/fonts/filter.ttf
    - family: Clear
      fonts:
        - asset: assets/fonts/clear.ttf
    - family: Clock
      fonts:
        - asset: assets/fonts/clock.ttf
    - family: Like
      fonts:
        - asset: assets/fonts/like.ttf
    - family: Reset
      fonts:
        - asset: assets/fonts/reset.ttf
    - family: Back
      fonts:
        - asset: assets/fonts/back.ttf
    - family: NotificationFilled
      fonts:
        - asset: assets/fonts/notification-filled.ttf
    - family: Share
      fonts:
        - asset: assets/fonts/share.ttf
    - family: Email
      fonts:
        - asset: assets/fonts/email.ttf
    - family: Bookmark
      fonts:
        - asset: assets/fonts/bookmark.ttf
    - family: Lock
      fonts:
        - asset: assets/fonts/lock.ttf

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

