import 'package:every_watch/backend/schema/structs/login_data_struct.dart';
import 'package:every_watch/backend/schema/structs/primary_image_struct.dart';
import 'package:every_watch/backend/schema/structs/watch_listing_struct.dart';
import 'package:every_watch/core/common/entities/user_entity.dart';
import 'package:every_watch/core/common/entities/watch_detail_entity.dart';

LoginDataStruct mapUserEntityToLoginData(UserEntity userEntity) {
  return LoginDataStruct(
    userId: userEntity.userId,
    email: userEntity.email,
    userName: userEntity.userName,
    firstName: userEntity.firstName,
    middleName: userEntity.middleName,
    lastName: userEntity.lastName,
    accessToken: userEntity.accessToken,
    refreshToken: userEntity.refreshToken,
    id: userEntity.id,
    rememberMe: userEntity.rememberMe,
    isLogin: userEntity.isLogin,
    isEmailVerified: userEntity.isEmailVerified,
    subscriptionTypeId: userEntity.subscriptionTypeId,
    subscriptionName: userEntity.subscriptionName,
    currencyName: userEntity.currencyName,
    tableauEmail: userEntity.tableauEmail,
    roles: userEntity.roles?.join(','), // Convert List<String> to String
  );
}

WatchListingStruct mapWatchDetailToListing(WatchDetailEntity detail) {
  return WatchListingStruct(
    id: detail.id,
    watchId: detail.watchId,
    manufacturerId: detail.manufacturerId,
    manufactureName: detail.manufactureName,
    manufacturerParentId: detail.manufacturerParentId?.toString(),
    isActiveManufacturer: detail.isActiveManufacturer?.toString(),
    manufacturerSlug: detail.manufacturerSlug,
    manufacturerURL: detail.manufacturerURL?.toString(),
    manufacturerPriority: detail.manufacturerPriority?.toString(),
    defaultManufacturerId: detail.defaultManufacturerId,
    defaultManufacturerName: detail.defaultManufacturerName,
    modelId: detail.modelId,
    modelName: detail.modelName,
    modelParentId: detail.modelParentId != null
        ? int.tryParse(detail.modelParentId.toString())
        : null,
    isActiveModel: detail.isActiveModel?.toString(),
    modelSlug: detail.modelSlug,
    modelURL: detail.modelURL?.toString(),
    modelPriority: detail.modelPriority?.toString(),
    defaultModelId: detail.defaultModelId,
    defaultModelName: detail.defaultModelName,
    referenceNumberId: detail.referenceNumberId,
    referenceNumber: detail.referenceNumber,
    referenceParentId: detail.referenceParentId != null
        ? int.tryParse(detail.referenceParentId.toString())
        : null,
    isActiveReferenceNumber: detail.isActiveReferenceNumber?.toString(),
    referenceNumberSlug: detail.referenceNumberSlug?.toString(),
    referenceNumberURL: detail.referenceNumberURL?.toString(),
    referenceNumberIsPending: detail.referenceNumberIsPending?.toString(),
    defaultReferenceNumberId: detail.defaultReferenceNumberId,
    defaultReferenceNumberName: detail.defaultReferenceNumberName,
    defaultReferenceNumberParentId:
        detail.defaultReferenceNumberParentId?.toString(),
    defaultReferenceNumberParentName:
        detail.defaultReferenceNumberParentName?.toString(),
    primaryImage: detail.primaryImage != null
        ? PrimaryImageStruct(
            url: detail.primaryImage!.url,
            preview320: detail.primaryImage!.preview320,
            preview480: detail.primaryImage!.preview480,
            preview768: detail.primaryImage!.preview768,
            preview960: detail.primaryImage!.preview960,
            preview1366: detail.primaryImage!.preview1366,
            original: detail.primaryImage!.original,
          )
        : null,
    imageUrl: detail.imageUrl?.toString(),
    sourceLink: detail.sourceLink,
    description: detail.description?.toString(),
    descriptionHtml: detail.descriptionHtml?.toString(),
    watchTitle: detail.watchTitle?.toString(),
    catelogNotes: detail.catelogNotes?.toString(),
    notes: detail.notes?.toString(),
    dimension: detail.dimension?.toString(),
    currencyName: detail.currencyName?.toString(),
    caseMaterialId: detail.caseMaterialId,
    caseMaterialName: detail.caseMaterialName,
    caseMaterialParentId: detail.caseMaterialParentId?.toString(),
    isActiveCaseMaterial: detail.isActiveCaseMaterial?.toString(),
    defaultCaseMaterialId: detail.defaultCaseMaterialId,
    defaultCaseMaterialName: detail.defaultCaseMaterialName,
    movementId: detail.movementId?.toString(),
    movementName: detail.movementName,
    defaultMovementId: detail.defaultMovementId?.toString(),
    defaultMovementName: detail.defaultMovementName,
    box: detail.box,
    isBox: detail.isBox,
    paper: detail.paper,
    isPaper: detail.isPaper,
    caseSizeId: detail.caseSizeId,
    caseSizeName: detail.caseSizeName,
    yearOfProduction: detail.yearOfProduction,
    conditionName: detail.conditionName,
    price: detail.price?.toString(),
    dialColorId: detail.dialColorId,
    dialColorName: detail.dialColorName,
    defaultColorId: detail.defaultColorId,
    defaultColorName: detail.defaultColorName,
    braceletMaterialId: detail.braceletMaterialId,
    braceletMaterialName: detail.braceletMaterialName,
    defaultBraceletMaterialId: detail.defaultBraceletMaterialId,
    defaultBraceletMaterialName: detail.defaultBraceletMaterialName,
    auctionLotPublishId: detail.auctionLotPublishId?.toString(),
    lotId: detail.lotId?.toString(),
    lotNumber: detail.lotNumber,
    eventPublishId: detail.eventPublishId?.toString(),
    eventPublishTitle: detail.eventPublishTitle,
    eventPublishEndDate: detail.eventPublishEndDate,
    eventSlug: detail.eventSlug,
    eventCountryName: detail.eventCountryName,
    eventCityName: detail.eventCityName,
    organizationName: detail.organizationName,
    organizationId: detail.organizationId,
    infoSourceId: detail.infoSourceId,
    infoSourceName: detail.infoSourceName,
    eventTypeId: detail.eventTypeId,
    minEstUsd: detail.minEstUsd,
    maxEstUsd: detail.maxEstUsd,
    minEstHkd: detail.minEstHkd,
    maxEstHkd: detail.maxEstHkd,
    minEstEur: detail.minEstEur,
    maxEstEur: detail.maxEstEur,
    minEstGbp: detail.minEstGbp,
    maxEstGbp: detail.maxEstGbp,
    minEstChf: detail.minEstChf,
    maxEstChf: detail.maxEstChf,
    minEstSgd: detail.minEstSgd,
    maxEstSgd: detail.maxEstSgd,
    hammerUsd: detail.hammerUsd?.toDouble(),
    hammerSgd: detail.hammerSgd?.toDouble(),
    hammerHkd: detail.hammerHkd?.toDouble(),
    hammerGbp: detail.hammerGbp?.toDouble(),
    hammerEur: detail.hammerEur?.toDouble(),
    hammerChf: detail.hammerChf?.toDouble(),
    hammerAed: detail.hammerAed?.toDouble(),
    hammerJpy: detail.hammerJpy?.toDouble(),
    isResultPending: detail.isResultPending,
    lotStatusId: detail.lotStatusId,
    slug: detail.slug,
    sellerOrganizationName: detail.sellerOrganizationName?.toString(),
    lastSeenDate: detail.lastSeenDate?.toString(),
  );
}
